### PR TITLE
Basic Styling

### PR DESCRIPTION
**Pull request by simonv3**
# What's Changed
- Added a logo
- Basic styling beyond the gh-pages defaults. 
# What's next
- ???

I didn't have the git hook installed yet, so dunno if that broke anything.

### CODE REVIEW

**Comment by RichardLitt** [comment]
How did you base this? Shouldn't it only have the last two commits?

**Comment by simonv3** [comment]
I just cloned

**Comment by RichardLitt** [comment]
Hmm. Weird. It looks like you based your changes on a new branch called gh-pages instead of fetching mine. I guess this is fine? I don't know what it will do to the commit history.

**Comment by RichardLitt** [comment]
:+1: :dancer:

**Pull request merged**
